name: dbt_CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  CI_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r ex03/dbt-requirements.txt

    - name: Set up dbt profile
      run: |
        mkdir -p ~/.dbt
        cp ex03/profiles.yml ~/.dbt/profiles.yml

    - name: Run dbt compile
      run: |
        cd ex03/dbt-project
        dbt compile

    - name: Run dbt build
      run: |
        cd ex03/dbt-project
        dbt build --fail-fast