name: ex02

on:
    workflow_dispatch:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    pytest:
        runs-on: ubuntu-latest
        steps:
            - name: Clone my repo
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'

            - name: Install packages
              run: |
                python -m pip install --upgrade pip
                pip install pytest

            - name: Run tests
              run: |
                cd ex02
                pytest tests/test_calculator.py --verbose
              